### ISSUE TITLE
Consonant ordering

### ISSUE THREAD

**Issue by rselvaraj** [oligoglot/mayal#1]
Just curious - any special reason for this altered consonant ordering about த, ந? A bit disorienting :smile: 
https://github.com/oligoglot/mayal/blob/e9b5f83787dc0e786466836388193a2a1519e35b/mayal.py#L16

**Comment by oligoglot** [comment]
Nice to see your comment on this, @rselvaraj. I wanted to discuss this paper with you and Vel after completing our work. The change in order was to group vallinam and mellinam together to show the neatness of pattern as in: https://github.com/oligoglot/mayal/blob/main/out/ettuthokai-consolidated.png @rpdwarf suggested this specific order to progress the place of articulation from the back to the front, I believe.

**Comment by oligoglot** [comment]
Comment addressed in the previous response
